version: "3"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest app/test.py
    depends_on:
      - events
      - db
  events:
    build: .
    command: python app/events.py
    depends_on:
      - db
  db:
    container_name: postgres-service
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example_db

networks:
  default:
    name: 'microsvcs'
    external: true