version: '3'

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example_db